name: I Love NL
favicon: null
layout_spectrum: 0.9411
typography_spectrum: 0.4565053361002356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd7c23'
    - '#ffffff'
    - '#000000'
    - '#00ff00'
    - '#008000'
  brandStrength: 0.5
  lightness: 0.2132908918429166
  saturation: 0.8112648653332144
  rhythmicContrast: 0.14928262075409293
purpose: []
