name: I Love NL
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd7c23'
    - '#ffffff'
    - '#000000'
    - '#00ff00'
    - '#008000'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.14928262075409293
purpose: []
